### ISSUE TITLE
Editor: Clear should clear cookie and disable Validate

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#125]
Two issues:
1. Validate should be disabled when there is no text in window (e.g., after a Clear)
2. Clear should also clear cookie

To recreate:

- Add some text and click Validate
- Now click Clear
- No text in window, Validate should be disabled (Issue1: it is not)
- Click Validate brings up the old chat which has been cleared (Issue2)

**Comment by cqx931** [comment]
**Question**
- Add some text and click Validate
- Now click 'Validate'
- Then click 'Clear'

Should the validated result(green box) also be cleared? (Also the execution result?)
And all buttons other than "Load URL" should be disabled when the editor is empty.

**Comment by dhowe** [comment]
That makes sense to me. Click clear to basically start over. Not sure if it should be empty or should say "Enter your script here", whichever is easier...

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/dialogic/pull/127

**Comment by dhowe** [comment]
Closing, but pls see #129
