### ISSUE TITLE
Editor: incorrect line selection edge case

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#132]
To recreate:
* double-click to select only line 2
* notice that line 3 is also included in output

![image](https://user-images.githubusercontent.com/737638/41442544-53e63512-706a-11e8-9441-8487565600f4.png)

**Comment by cqx931** [comment]
Can't reproduce this now
![image](https://user-images.githubusercontent.com/3056154/42292437-e1402f86-7fd2-11e8-8150-b1b07c821380.png)

**Comment by dhowe** [comment]
I still see this. Did you double-click to select the entire line (as shown in the first image) ?

**Comment by cqx931** [comment]
Fixed this issue [here](https://github.com/dhowe/dialogic/commit/a8f12517b8476edd69cc0638a58e7a87605d9422), close
