### ISSUE TITLE
Auto-generate docs

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#14]
generate html class documentation (like javadoc), preferably from within Visual Studio

**Comment by cqx931** [comment]
Within Visual Studio: [GhostDoc](https://marketplace.visualstudio.com/items?itemName=sergeb.GhostDoc)
Or [doxygen](https://github.com/doxygen/doxygen)?

**Comment by dhowe** [comment]
whatever is easiest, preferably within VSS

**Comment by dhowe** [comment]
done via doxygen...
