### ISSUE TITLE
XML error in editor (Firefox)

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#155]
Firefox only  (no symptoms)
```
XML Parsing Error: not well-formed
Location: http://localhost:50945/dialogic/editor/
Line Number 52, Column 26: editor:52:26 

```
![image](https://user-images.githubusercontent.com/737638/45925596-48d26300-bf4b-11e8-99ea-0f1922663c06.png)

**Comment by cqx931** [comment]
I don't see this issue in the console anymore
