### ISSUE TITLE
Editor: UI issues [viz]

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#160]
See #161. Two issues with html/css/jquery in editor/data/combined.html on the new 'viz' branch.

To recreate:
1. open this file in firefox
2. click one of the nodes
3. then click 'edit' node in the toolbar
4. __First issue__: textarea does not update with code (see combined.html::880)
5. Now click in the textarea and notice the code show up
6. __Second issue__: formatting of line numbers

@cqx931 lets discuss

![image](https://user-images.githubusercontent.com/737638/47711613-963f9f80-dc70-11e8-9679-9e9189d988fb.png)

**Comment by cqx931** [comment]
Please check
https://github.com/dhowe/dialogic/pull/162

- fixed text area refresh issue
- fixed line numbers
- implemented split view
- now the manipulation bar for viz disappears after resizing the div, this seems to be from the viz js file. If we do decide to use viz, I can fix it later.

**Comment by cqx931** [comment]
fixed
