### ISSUE TITLE
Visualizer/Editor Specification

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#161]
Overview
---------------------
To provide an interface for visualizing a set of Chats as a network diagram, where individual chats can then be created/deleted/edited. Visualization component should support pan, zoom, save, load, etc. Labels should be rectangular and arranged naturally with a physics model. Children of a chat should be collapsible (hidden with a single-UI action) as well. The editor interface should be very similar to the current editor.

Proposed Interface
---------------------
* Two Panel window: network on left, editor on right 
* Slide vertical separator to control how much of each you see
* Or close one or the other completely with X buttons

Proposed UI Actions 
---------------------
#### NETWORK
* Double-click on node to open in editor
* Double-click not on node creates new Node
    * New Node must be named when created
    * Blank editor opens with 'enter your code here'
* Right-click context menu: 'Delete node'
* Save button (saves all chats into single file for download)
* Options to load a file (or folder), or URL containing one or more Chats
* Options to collapse/hide all children of a Node [v0.2]

#### EDITOR
* Current editor buttons remain on editor side
* Except LOAD-URL which moves to [NETWORK]
* Save button (saves single chat to file for download)

Proposed Server API (Ajax)
---------------------
* visualize: takes a file, folder, or URL of chat data , and returns JSON representing the nodes, edges, and contents
* validate:  takes the script for one or more chats and returns JSON either 'ok' or an error object
* execute:  takes the (pre-validated) script for one or more chats and returns (as JSON) either its output, or an error object

__more detail to follow here, however we can think of each call (an AJAX Post) as passing one or more chats, and receiving a JSON-formatted response back with the data requested__

Starting points:
---------------------
* https://bl.ocks.org/cjrd/6863459
* http://visjs.org/examples/network/other/manipulation.html ([viz] branch is a start based on this)
* http://bl.ocks.org/robschmuecker/7880033

**Comment by cqx931** [comment]
Question: 

- what does the network show if the loaded file contains only one chat? Just one single node?
- what are possible relationships between two chats? Is it always going to be directional (arrow: one chat following another)?
- What is the scenario when the API needs to take more than one chat, if validate button is only in the editor window(one chat at a time)?

**Comment by dhowe** [comment]
> - what does the network show if the loaded file contains only one chat? Just one single node?

Yes, though perhaps it should be minimized or closed in such cases

> - what are possible relationships between two chats? Is it always going to be directional (arrow: one chat following another)?

Relationships are determined by GO and ASK/OPT commands, so if Chat A has a GO #B and Chat B has a GO #A it would be bi-directional (or two directional edges, one going each wa). Note that there can also be self-loops, as in the test data, where a Chat goes to itself (under some condition).

> - What is the scenario when the API needs to take more than one chat, if validate button is only in the editor window(one chat at a time)?

As best I can tell there are 3 API cases: visualize(), validate(), execute(). Visualize takes one or more files, each of which may contain one or more chats. Validate and Execute take strings which contain one or more Chats. All 3 may take options (such as 'use Validators')

**Comment by cqx931** [comment]
Proposed Interface
---------------------

- [ ]  Two Panel window: network on left, editor on right 
- [ ]  Slide vertical separator to control how much of each you see
- [ ]  Or close one or the other completely with X buttons

Proposed UI Actions 
---------------------
#### NETWORK
- [ ]  Double-click on node to open in editor
- [ ]  Double-click not on node creates new Node
    - [ ]  New Node must be named when created
    - [ ]  Blank editor opens with 'enter your code here'
- [ ]  Right-click context menu: 'Delete node'
- [ ]  Save button (saves all chats into single file for download)
- [ ]  Options to load a file (or folder), or URL containing one or more Chats
- [ ]  Options to collapse/hide all children of a Node [v0.2]

#### EDITOR
- [ ]  Current editor buttons remain on editor side
- [ ]  Except LOAD-URL which moves to [NETWORK]
- [ ]  Save button (saves single chat to file for download)

**Comment by cqx931** [comment]
Please check the latest commit here:
https://github.com/dhowe/dialogic/commit/d8265031c5407d60d2e93359d31c45a358deac4a
(Sorry for pushing directly to your repo, I realized that I forgot to change the git remote settings after recloning the project from git)

- Added the server functions for validate/update buttons
- Implemented basic interface functions and cleaned up the visual
- I modified a bit on the server code, one for CORS, another one for empty execute result(I changed this because of strange JSON parsing issue when it is empty). Please let me know if you think the change is problematic.

A few issues to be solved
- line breaks and special characters in result and executeResult
- Execute with selection is not working properly

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/dialogic/pull/164

- I made a sample json file based on the sample data we had before.
- I moved the "load-chats" button above the editor/network viewer, in the current specs, it is saying that it should be in the network panel. I think it makes more sense if its always visible?
- I'm not sure how it should handle a folder, especially when it comes to file validation. So I have implemented loading from one single file for now.

**Comment by dhowe** [comment]
Good work. Next steps:

* Think about Save-Chats? Should save full network to single file
* Graph nodes should be rectangles instead of ovals
* Double-click: on-node, should open in editor; off-node, should add new chat with prompt for name
* Remove Node-menu, use double-click instead, and add 'delete' as context menu (right-click) option?
* Bug? Node menu disappears sometimes, no way to get back
* Fix alignment of 'Use Validators' button
* Load-folder should load all files in folder (v2?)

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/dialogic/pull/165

Done:
- Support multiple file loading
- Change shape from ellipse to rectangle 
- Remove node-menu
- Support double click & right click delete context menu
- Add 'Save Chats' button
- Add node label title for chat-editor

To Do:
- Implement 'save chats'
- Selection-handling in JavaScrip
- The default node editing popup is too much for our use case. But because the network view is a canvas, it would be hard to directly edit the node name on the node.(Or is there other workarounds?) What are other ways to change node labels after node is created? (How about node label title for chat-editor?)

**Comment by cqx931** [comment]
Please check the latest PR:
- Implemented 'save chats'
- Added node label editing

TODO:
- Selection-handling
- Add edges?

Somehow I have issues accessing the following file from lint( https://jsonlint.com/css/style.css), could you please check whether that happens to you as well? It could be just my internet issue.

**Comment by dhowe** [comment]
I don't have issues with that .css file.
A few minor issues you can see below (Firefox):
1. HTML elements overlapping the vertical divider
2. Capitalization no matching between node and editor title

![image](https://user-images.githubusercontent.com/737638/50738382-27ea0100-120e-11e9-958d-1d09cb667a92.png)

**Comment by dhowe** [comment]
A few minor issues you can see below (Firefox+Chrome):
1. HTML elements overlapping the vertical divider
2. Capitalization no matching between node and editor title

![image](https://user-images.githubusercontent.com/737638/50738382-27ea0100-120e-11e9-958d-1d09cb667a92.png)

**Comment by dhowe** [comment]
The CORS issues should be fixed now as well (note that the server now returns a JSON _object_, so need for parsing it)

**Comment by dhowe** [comment]
Also, re: our earlier conversation, chat names _must always_ stay in sync with their name in the file. So we actually don't need to be able to edit chat names outside of the editor. BUT, if the name is changed within the editor then the name on the node needs also to edit.

![screen shot 2019-01-07 at 12 02 12 am](https://user-images.githubusercontent.com/737638/50738513-c6c32d00-120f-11e9-8176-ee880b43409e.png)

**Comment by cqx931** [comment]
I didn't realize that the name of the node should be in sync with the chat name after CHAT. If this is the case. After the user creates a new node called "NewChat", shouldn't this also automatically added to the corresponding script?

**Comment by cqx931** [comment]
Also I don't see the HTML overlapping issue. (both Firefox & Chrome)
![image](https://user-images.githubusercontent.com/3056154/50951238-679f3a00-14e7-11e9-941f-ebbdb8822f4e.png)

**Comment by dhowe** [comment]
> I didn't realize that the name of the node should be in sync with the chat name after CHAT. If this is the case. After the user creates a new node called "NewChat", shouldn't this also automatically added to the corresponding script?

Yes, good point. And yes, they must always be in sync. There is a function to generate a unique name if one is not provided. Maybe use that for the name rather than 'NewChat' ?

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/dialogic/pull/167

- fixed HTML overlapping issue
- change from json format to dialogic script in load/save chats
- use Time stamp instead of 'NewChat'

For now, changing chat name from editor doesn't change the corresponding label in the network.
Since there is no save button for a single chat, the label can be updated from editor to network in the following scenarios:
1. After validation (this makes most sense to me)
2. After the script is executed
3. Adding a sync button ?

**Comment by cqx931** [comment]
Yes, sending the full set of chats to the server makes more sense here.

A few questions:
1.Does that mean there is no switching among chats anymore? What happens if the user load multiple files? Can we separate the file structure from the visualizer and have something similar like the tabs in code editor? In this case, if the user changes anything to one file, it can be saved again as the original file.

2. What happens if one creates/delete/rename a new node/edge in the visualizer in this scenario? At this point it makes more senses to me if we could keep all the input within the editor and let the visualizer be a pure visualizer. This would make things more straightforward and less confusing.

**Comment by dhowe** [comment]
NEXT:
- get execute working
- auto-scroll in editor to chat selected in graph
- add arrows to edges in graph

**Comment by dhowe** [comment]
NEXT:
- get execute working
- auto-scroll in editor to chat selected in graph
- add arrows to edges in graph

**Comment by dhowe** [comment]
> I'm not sure about "maintain state of editor/graph on [validate]". What are the use cases of these states?

1. We don't want the layout (positions of nodes) to change for nodes that haven't changed. Ideally only changed nodes should be updated. 

2. Consider the case where the user has panned or zoomed the graph to see the part that they are interested in. Then they make a small change and validate() again. First, the pan and zoom settings should persist. And second, for this to make sense, the nodes need to be in the same place.

**Comment by dhowe** [comment]
> [execute] multiple chats only returns the result from the first chat. Is this the expected result?
checking into this

**Comment by dhowe** [comment]
> Handle validate/execute selection (-> only update network if the user tries to validate all the chats) [implemented]

Why are we not updating the network (same as in other cases) ? For example, if a user changes a Chat label, then validates just that one Chat, then that node's should be updated as well. Similarly if a user adds or removes a GO command, then validates just the one Chat, then that node's outgoing arrows should be updated as well. 

The general algorithm for graph updates after a validate is:
1. Get the results from the validate() call
2.  call toNetworkData() to get nodes and edges
3. compare set of result nodes to existing nodes in graph
  3a. if any new nodes are missing in the graph, add them
  3b. if any existing graph nodes are missing in the new data, delete them  (only if not a selection)
  3c. if a new nodes exists in the graph with a different label, update the graph node's label**
4. do the same for edges

** how to tell when that a label change is not a delete and add new node?

**Comment by dhowe** [comment]
@cqx931 Note: I started work on graph-update and left TODO's in-line for you

**Comment by cqx931** [comment]
I remember that we have talked about issues with saving data in cookies, so I added pan/zoom settings, editor scroll-position & line-number to local storage instead. These state settings can't be resumed in loadFromStorage() yet. See TODO

Partial selections. I have tested with selections and it seems to me that most of the things you have mentioned already function as expected except this issue: https://github.com/dhowe/dialogic/issues/173

**Comment by cqx931** [comment]
Please check the latest commit in viz branch: https://github.com/dhowe/dialogic/tree/viz

**Comment by cqx931** [comment]
@dhowe  Can this be closed now?

**Comment by valuesindesign** [comment]
yes
