### ISSUE TITLE
Editor: selection across chats

### ISSUE THREAD

**Issue by cqx931** [dhowe/dialogic#173]
If I try to make a selection across chat and leave one chat title out of selection, the network will regard the chat content without title as a new node.
![image](https://user-images.githubusercontent.com/3056154/52007379-55883a00-249c-11e9-93a8-9537254d376d.png)

**Comment by dhowe** [comment]
I'm not sure this auto-titling of Chats really works any more... What do you recommend here? Throw an error?

**Comment by dhowe** [comment]
@cqx931  ?

**Comment by cqx931** [comment]
This should be handled as we discussed in the latest commit in viz branch.

**Comment by dhowe** [comment]
I remember that we talked about it, but where is the record? In 48418a4d79 ?

**Comment by cqx931** [comment]
We talked about this in telegram, the fix is at https://github.com/dhowe/dialogic/commit/448418a4d7959b4b5314ee1cb5b28498a3eef8c7
