### ISSUE TITLE
Editor: Auto-layout not working

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#174]
After load from file:
![screen shot 2019-02-22 at 8 43 38 pm](https://user-images.githubusercontent.com/737638/53243417-bb09c800-36e2-11e9-8511-73c69d1d8f25.png)

**Comment by dhowe** [comment]
After manual 'validate', parts are off-screen:

![image](https://user-images.githubusercontent.com/737638/53243749-d2958080-36e3-11e9-8970-6757f0575c40.png)

**Comment by dhowe** [comment]
pls check @cqx931

**Comment by cqx931** [comment]
this should be fixed, please check https://github.com/dhowe/dialogic/pull/175
