### ISSUE TITLE
Spec for syntax highlighting

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#176]
Seems to me syntax highlighting isnt working correctly, however I need a spec to check:

![image](https://user-images.githubusercontent.com/737638/60746875-8a1e8700-9f4f-11e9-9f53-d6f00d3cc172.png)

**Comment by cqx931** [comment]
this is the image you posted as an example specs that I used to write the syntax highlighting
![image](https://user-images.githubusercontent.com/3056154/60757334-2b9ceb80-9fd7-11e9-9d2a-6f56bc34b44a.png)

More discussions on syntax highlighting
https://github.com/dhowe/dialogic/issues/88

**Comment by dhowe** [comment]
perfect, can we move to this image to the wiki somewhere?

**Comment by dhowe** [comment]
Note also that this is NOT the syntax highlighting we have now... (for example, groups have no color)

**Comment by cqx931** [comment]
okay, let me create one with the current color scheme in use.

**Comment by cqx931** [comment]
Most of the items seem to work except html entity and group with variable, I don't see any issues with groups though?
![image](https://user-images.githubusercontent.com/3056154/60758826-acfd7980-9fe9-11e9-8566-76fae09ae062.png)

**Comment by cqx931** [comment]
Updated here: https://github.com/dhowe/dialogic/wiki/Workbench
