### ISSUE TITLE
Position limitation of the middle bar

### ISSUE THREAD

**Issue by cqx931** [dhowe/dialogic#178]
Now I can move the middle bar(between the visualizer and the editor) off window width, which is a bit weird and confusing. It should always stay on screen or maybe also a minimum width for the visualizer.

**Comment by dhowe** [comment]
Yes, this is a bug. But it should be easy to close the network window. If we have that, then a minimum width (50px perhaps) is fine.

**Comment by cqx931** [comment]
This is fixed in this commit https://github.com/dhowe/dialogic/pull/182/commits/bf91c8c69e3a1a4831a7cf6e431e849fcc5a87f3
