### ISSUE TITLE
Syntax: '!' should not be colored except as operator in metadata

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#180]
![Screen Shot 2019-07-06 at 3 16 36 PM](https://user-images.githubusercontent.com/737638/60760287-15a42080-a001-11e9-8c1a-b3866c140833.png)

**Comment by dhowe** [comment]
I'm still seeing this in 2e7ae4470e9e

![image](https://user-images.githubusercontent.com/737638/60842063-415e0c80-a1a1-11e9-8a20-15af6fb5f025.png)

**Comment by cqx931** [comment]
https://github.com/dhowe/dialogic/commit/84338c47fe86048c3f135b2b6eefcd1dc6a4b9b6
