### ISSUE TITLE
Lines get 'stuck' with error highlighting

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#185]
Recreate:
 -- create a line with an error, e.g., CHAT c 2
 -- line is correctly highlighted
 -- fix error and re-validate
 -- line stays highlighted as if still an error

![image](https://user-images.githubusercontent.com/737638/61172287-2d732b80-a550-11e9-9f8e-2b9620d83302.png)

**Comment by cqx931** [comment]
Fixed here: https://github.com/dhowe/dialogic/pull/190/commits/9464cd59ed501db58b3efdbe10ce24985780a329
