### ISSUE TITLE
Adjust colors for dark theme

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#186]
Should be something more like below:

- [x] bg should be lighter, similar to #1C1E1F below
- [x] whites should be off-white
- [x] colors should be more subtle (especially reds/purples)

![image](https://user-images.githubusercontent.com/737638/61172338-de79c600-a550-11e9-9017-154c5ee38cd8.png)

![image](https://user-images.githubusercontent.com/737638/61172472-c881fa80-a57c-11e9-8275-e43b4e53b3b4.png)

**Comment by cqx931** [comment]
Done https://github.com/dhowe/dialogic/pull/190/commits/bfdf77870d7948d32a8ca5499da15fb400986f62
