### ISSUE TITLE
Between CHAT arrows not showing

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#187]
In the graph below, there should be an arrow from 'start' to 'Game1':

![image](https://user-images.githubusercontent.com/737638/61172418-121e1580-a57c-11e9-847a-d0478b169757.png)

**Comment by cqx931** [comment]
Fixed here: https://github.com/dhowe/dialogic/pull/190/commits/ac3892a053552ee2d8a5cacc986b2a9e4f90f71d
