### ISSUE TITLE
Behavior on validate selected text

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#188]
What is the expected behavior of the network panel when (partial) text is selected and validated ?

**Comment by cqx931** [comment]
I think the network panel should always display network of the whole text, for better performance the visual could also indicate the selection in some ways, but this is not to be expected from the current version.

**Comment by dhowe** [comment]
ok, lets add a ticket for that (perhaps just make the nodes from the non-selected text partially transparent, or gray)

**Comment by cqx931** [comment]
close this and see #189
