### ISSUE TITLE
Color and vertical alignment of elements in top bar

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#191]
Two items:
1. remove the heavy red from the top bar (i think off-white/gray is fine)
2. the vertical alignment seems sort of random (each bit of a text has a different baseline)

![image](https://user-images.githubusercontent.com/737638/61221784-32b6ae80-a6e7-11e9-8dc0-2da710232bcf.png)

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/dialogic/commit/35cb386147e91b76a7cb803bd444a11d3a2dca21

**Comment by dhowe** [comment]
looks good except the load/save buttons are hard to see in light mode

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/61229886-fd19c180-a6f6-11e9-9dd6-8f34ced98c35.png)

**Comment by cqx931** [comment]
color fix https://github.com/dhowe/dialogic/commit/dbf88c56430d4651b16e488d482c1cc28ae6f6a5 for this issue. I kept the pink color for light theme, as they don't seem that heavy on white background.
