### ISSUE TITLE
Editor: add 'use TendAR validators' checkbox on page, default false

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#20]
Add a checkbox to the form, which should be automatically sent along with the POST request. Then I can handle the modification of the LintServer

**Comment by cqx931** [comment]
Is this already handled here?
https://github.com/dhowe/dialogic/blob/master/weblint/data/index.html#L73

**Comment by dhowe** [comment]
No. This is a checkbox on the form itself, which decides whether the Linter uses 'external validators', which are specific to the TendAR project. For example, every Chat in the TendAR project MUST have either "type" and "stage" metadata, or a "noStart=true" metadata tag, or it will throw an Exception. But this is not part of Dialogic itself, only part of the TendAR app. Does this make sense?

[x] Use TendAR validators

**Comment by dhowe** [comment]
Note: this is lower priority than #64

**Comment by dhowe** [comment]
the checkbox is there but commented, just needs to be hooked up

**Comment by dhowe** [comment]
note that this setting should be persistent across validate/execute/page-refresh

**Comment by dhowe** [comment]
@cqx931 is this data-field being sent with the form at present?

**Comment by dhowe** [comment]
the only thing that needs to be changed in Editor.cs is [line 188](https://github.com/dhowe/dialogic/blob/master/editor/Editor.cs#L188)
instead of always sending false, we send the inverse of the checkbox value,
so if UseTendARValidators is true, we send false, and vice versa

**Comment by cqx931** [comment]
@dhowe The checkbox has already be added, can this be closed now?
