### ISSUE TITLE
Linter: allow URL for script-file, in addition to copy paste

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#21]
You can use the 'LoadUrl' button on this [page](https://codebeautify.org/jsonvalidator) as an example.

We should be able to use a github raw URL, or a Google-docs URL.

Start by testing with URLs of these files (in RAW mode): https://github.com/dcannizzaro/tendAR/tree/ca06ee409fd15420135e9567ed921645b337b0b4/TendAR/Assets/Libraries/Dialogic/GuppyScripts

For example: https://raw.githubusercontent.com/dcannizzaro/tendAR/ca06ee409fd15420135e9567ed921645b337b0b4/TendAR/Assets/Libraries/Dialogic/GuppyScripts/gscript.gs.txt?token=AAtBZge0aTiAfaPesTi2C3SE8_Zssiuwks5ay-qjwA%3D%3D 

For the Google docs case, see also: #25

**Comment by cqx931** [comment]
the testing URLs above are no longer valid

**Comment by dhowe** [comment]
The files are here: https://github.com/dcannizzaro/tendAR/tree/master/TendAR/Assets/Libraries/Dialogic/GuppyScripts

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/dialogic/pull/43/commits/806ab63e0959847fdf01c2d0b149d65bc8940b24
