### ISSUE TITLE
NullReferenceException in unit test result 

### ISSUE THREAD

**Issue by cqx931** [dhowe/dialogic#22]
Got this error from `tests -> Run Item` after merging the latest commit 
<img width="1296" alt="screen shot 2018-04-01 at 9 10 38 am" src="https://user-images.githubusercontent.com/3056154/38173430-a3c042e4-358c-11e8-9590-0768944f0215.png">

**Comment by dhowe** [comment]
I don't see this error in the current commit: 82fabbb36e

![image](https://user-images.githubusercontent.com/737638/38174493-873450f6-3600-11e8-9aab-c81447a3b240.png)
