### ISSUE TITLE
Ability to query event for duration in milliseconds

### ISSUE THREAD

**Issue by mitchmastroni** [dhowe/dialogic#29]
I'm currently accomplishing this with the following line in Event.cs:
```
        public UpdateEvent(Command c) {
            this.data = c.realized;
            this.data.Add("duration", c.ComputeDuration()); // <----
        }
```

**Comment by dhowe** [comment]
I'm not sure this is what you want -- can you tell me the use-case? That duration is actually the delay _before_ the event is sent
