### ISSUE TITLE
Resumes not working as expected

### ISSUE THREAD

**Issue by mitchmastroni** [dhowe/dialogic#32]
Steps to Reproduce: Parse the following chats. Trigger CORE_Long_Interruptable, while it is playing, trigger CORE_Short_Interruption.
```
CHAT CORE_Long_Interruptable {type=poke, stage=CORE}
SAY Oh, it's you...
SAY It's been a long time. How have you been?
SAY I've been really busy being dead.
SAY You know
SAY After you MURDERED ME
SAY Okay. Look. We both said a lot of things that you're going to regret.
SAY But I think we can put our differences behind us.
SAY For science.
SAY You monster.

CHAT CORE_Short_Interruption {type=shake, stage=CORE}
SAY Stop that.
```

Expected: CORE_Long_Interruptable will resume after CORE_Short_Interruption 

Actual: CORE_Long_Interruptable does not resume after CORE_Short_Interruption

**Comment by dhowe** [comment]
Yes, a bug indeed -- fixed
