### ISSUE TITLE
Linter: set max-width of 'Execute' div, so that output wraps if too long

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#42]
To avoid a long line like below (but not for the 'validate' output, only the 'execute' output)

![screen shot 2018-04-12 at 9 27 23 pm](https://user-images.githubusercontent.com/737638/38680265-75cb4734-3e98-11e8-890b-b1fac13dc568.png)

**Comment by cqx931** [comment]
added here: https://github.com/dhowe/dialogic/pull/43

**Comment by dhowe** [comment]
I don't see this happening (see below), so I'm adding a max-width tag

![image](https://user-images.githubusercontent.com/737638/38730119-f154a792-3f47-11e8-9bb6-5d04d19e9066.png)

**Comment by dhowe** [comment]
In fact, what we want is the blue to be a max-width of 620px always. While the green and red divs to start at 620px, but to extend as far as needed if the text is longer

**Comment by dhowe** [comment]
I've added the max-width tag, but please take care of the 2nd part ('the green and red divs should start at 620px wide, but then extend as far as needed if the text is longer')
