### ISSUE TITLE
Global timing constant

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#47]
[Pending Question]

I've implemented a constant for all Command event durations, called Defaults.GLOBAL_TIME_SCALE, which defaults to 1. This affects only the scheduler timing (that is, the duration for each Command). Setting it to 1.5, for example, would extend these durations by 50% (thus slowing the system down)

What, if any, other timing properties should be affected here? Should this include literal properties (set by either the game or a Chat author) as well? For example, if an author specifies an Ask timeout of 5 seconds, should this be scaled as well? I think not, but want to verify the thinking here

**Comment by dcannizzaro** [comment]
Yea I think that sounds good.  Agree that it's probably better not to affect things like the ask timeout.

**Comment by dhowe** [comment]
Ok, I'll close for now... reopen if anything becomes apparent
