### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [dhowe/dialogic#53]
Hello, I just made a logo for your project, hope you like it.

![dl2](https://user-images.githubusercontent.com/35619342/38905307-e313cb34-427d-11e8-8e91-356302799435.png)

![dl1](https://user-images.githubusercontent.com/35619342/38905357-3c4a9660-427e-11e8-9fc3-2d55278f52bb.png)

If you liked it, let me know which variation and I'll upload the files on a PR. It is open to any modification.

**Comment by dhowe** [comment]
I quite like the logo (especially the double shadow), but I'm not sure its quite right for the flavor of this project. If you're interested in trying another take, let me know, and we can discuss some other possible directions. In any case, thanks for all the good work - its much appreciated...

**Comment by michaelizer** [comment]
Hello, glad you liked the style. I can try some combinations between dialog globes (round and square) and a puzzle for example (was another idea I had) or something else that represents "logic". What do you have in mind?

**Comment by dhowe** [comment]
Closing for now, but happy to re-open for more discussion / updates
