### ISSUE TITLE
Add pluralization function

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#64]
Using branch 'pluralize', fill in the [Pluralize() function in  Pluralizer.cs](https://github.com/dhowe/dialogic/blob/pluralize/dialogic/Pluralizer.cs) with ported code from RiTa (either java or js, whichever is simpler)

I've created [the test code in DialogicTests.cs](https://github.com/dhowe/dialogic/blob/pluralize/tests/DialogicTests.cs#L11). When you open the branch and run the tests, this should be the only test that fails.

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/dialogic/pull/73
