### ISSUE TITLE
Linter: highlight a section of text to validate/execute

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#70]
@cqx931 any difficulty here? basically, if there was any highlighted text, the linter would ONLY send that text, ignoring the rest...

if this is relatively easy, pls go ahead and add -- otherwise, lets discuss

**Comment by cqx931** [comment]
Should be relatively easy according to this:
https://stackoverflow.com/questions/5379120/get-the-highlighted-selected-text
