### ISSUE TITLE
Editor: Replace lined-text-area with CodeMirror 

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#83]
https://codemirror.net/

Add support for:

* Multiple undo/redo
* Search and replace 
* ~~Resizing of text-area~~ (done?)

Maintain support for:
* highlight section to validate
* correct line #s on errors (for highlighted and full text)

Fix
* ~~Red highlighting of spelling errors~~ (done)

**Comment by cqx931** [comment]
* Multiple undo/redo https://codemirror.net/doc/manual.html#api_history
* Search and replace  https://codemirror.net/doc/manual.html#addon_search

**Comment by cqx931** [comment]
Please check https://github.com/dhowe/dialogic/pull/115
Maintain support for:
* highlight section to validate (done)
* correct line #s on errors (for highlighted and full text) (done)

**Comment by dhowe** [comment]
I see the wrong line number of errors when partial script is highlighted/validated:

Recreate: highlight bottom 2 lines below, hit 'validate'

```
line1
line2
{ line 3 error
```

![image](https://user-images.githubusercontent.com/737638/40618405-fd80943c-62c3-11e8-8121-72a563705fed.png)
