### ISSUE TITLE
Differences between 'validate' and 'execute' button

### ISSUE THREAD

**Issue by cqx931** [dhowe/dialogic#85]
Is this correct? It is confusing for me.
<img width="1067" alt="screen shot 2018-05-10 at 2 04 22 pm" src="https://user-images.githubusercontent.com/3056154/39885680-379e7dc2-545b-11e8-8f57-bec2dc23745d.png">
<img width="1043" alt="screen shot 2018-05-10 at 2 04 27 pm" src="https://user-images.githubusercontent.com/3056154/39885685-38df21dc-545b-11e8-9418-d8860f1a049d.png">

**Comment by dhowe** [comment]
Yes, indeed that is a bug (good catch!!). The idea is that you first 'validate', and then (IF OK) you can 'execute'. So the execute button should only be enabled if there is NOT an error.

**Comment by dhowe** [comment]
See #125
