### ISSUE TITLE
Editor should store/restore current text

### ISSUE THREAD

**Issue by dhowe** [dhowe/dialogic#99]
Use-Case: writer is working in editor and accidentally hits refresh, all work is lost.
Should instead repopulate the textarea with last text state

Note: this can be done on its own (if very simple) OR in conjunction with #83

**Comment by cqx931** [comment]
I didn't find anything very helpful for this issue within codeMirror.
Maybe use cookies to store the content then repopulate it if there is a saved version in the browser?

**Comment by dhowe** [comment]
that would work

**Comment by dhowe** [comment]
Is it possible to just always start with the cookie data if the cookie is there (instead of 'enter code here' ?

**Comment by cqx931** [comment]
Yes, please check the latest commit in the PR: #117

**Comment by dhowe** [comment]
This seems not to work in Chrome. Can you check?

**Comment by cqx931** [comment]
loadFromStorage() is currently commented out, probably because editor & network state resume is not completely finished yet, I wrote some of the functions, but not everything is working. I can open a separate ticket to follow up the details for this
